#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

set -o errexit

echo "Running Pre-Commit Git hooks"

# Fetching Env Vars
MYSQL_USER=$(grep MYSQL_USER .env | xargs)
MYSQL_USER=${MYSQL_USER#*=}

MYSQL_PASSWORD=$(grep MYSQL_PASSWORD .env | xargs)
MYSQL_PASSWORD=${MYSQL_PASSWORD#*=}

MYSQL_DATABASE=$(grep MYSQL_DATABASE .env | xargs)
MYSQL_DATABASE=${MYSQL_DATABASE#*=}

DB_PATH=$(grep DB_PATH .env | xargs)
DB_PATH=${DB_PATH#*=}

CURRENT_DATE_TIME="`date +%Y-%m-%d-%H-%M-%S`"
NEW_FILE="${DB_PATH%*.sql}"-$CURRENT_DATE_TIME.sql


# Export the Configuration
echo "Exporting the Configuration"
docker exec drupal composer drupal config:export

# Export the Database dump
mv $DB_PATH $NEW_FILE
echo "Exporting Database Dump"
docker exec drupaldb mysqldump --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE  > $DB_PATH

